/*
 * SteeringWheelInputModule -- observes the raw MFW left-roller press before
 * the stock keyboard stack maps both it and the centre-console DDS to the
 * same HMI key (INC_MENU_ENTER / Key.DDS_SELECT).
 *
 * DSIKeyPanel supports multiple listeners.  The stock keyboard service and
 * TerminalMode already register independent instance-0 listeners, so this
 * module adds a third listener for ATTR_KEY2 only.  The raw marker lets the
 * patched CarPlay controller suppress only the later collapsed DDS_SELECT
 * generated by key 40; key 16 (centre DDS) remains ordinary CarPlay Select.
 *
 * The action itself is gated by the VC's last confirmed main context.  The
 * stock IMMICombiScreenChangeManager reports MAIN_CONTEXT_NAVIGATION_MAP=20;
 * our private cluster render contexts must not be confused with this tab ID.
 *
 * Copyright (c) 2026 LuKa (@LuKa_dev)
 */
package com.luka.carplay.core;

import com.luka.carplay.framework.Log;

import de.audi.app.terminalmode.keyevents.KeyState;
import de.audi.atip.mmicombi.IMMICombiScreenChangeManager;
import de.audi.atip.mmicombi.exchange.MMICombiDisplayStatus;

import org.dsi.ifc.keypanel.DSIKeyPanel;
import org.dsi.ifc.keypanel.DSIKeyPanelListener;
import org.osgi.framework.ServiceRegistration;

public final class SteeringWheelInputModule implements Module {
    private static final String TAG = "MfwInput";

    private static final int DSI_INSTANCE = 0;
    private static final int KBD_MFW = 4;
    private static final int KBD_MFW_3GP = 8;
    private static final int KEY_DDS = 16;
    private static final int KEY_MFW_ROLLER_LEFT = 40;
    private static final int KST_RELEASED = 0;
    private static final int KST_PRESSED = 1;
    private static final int ATTR_VALID = 1;
    private static final long COLLAPSED_SELECT_WINDOW_MS = 600L;

    /** Configurable duration (ms) for press-and-hold on the left wheel to cycle between CarPlay and stock Audi maps. */
    public static final long LONG_PRESS_DURATION_MS = 5000L;

    private static final Object SELECT_LOCK = new Object();
    private static long pendingPressUntil;
    private static long pendingReleaseUntil;

    private java.util.Timer longPressTimer;
    private java.util.TimerTask currentLongPressTask;
    private boolean longPressHandled;

    private final RawKeyListener listener = new RawKeyListener();
    private FrameworkRef.ServiceHandle keyPanelHandle;
    private FrameworkRef.ServiceHandle combiManagerHandle;
    private boolean keyPanelMissLogged;
    private DSIKeyPanel keyPanel;
    private volatile IMMICombiScreenChangeManager combiManager;
    private ServiceRegistration listenerRegistration;
    private volatile boolean running;

    public String name() { return "mfw-input"; }

    public synchronized boolean start(FrameworkRef fw) {
        /* combiManager is optional, so it must NOT be part of the already-started test - it would
         * make every retry re-register the listener. */
        if (listenerRegistration != null && keyPanel != null) return true;
        if (fw == null || !fw.isReady() || fw.serviceManager() == null) return false;

        FrameworkRef.ServiceHandle handle = fw.getServiceHandle(DSIKeyPanel.class);
        if (handle == null || !(handle.service() instanceof DSIKeyPanel)) {
            if (handle != null) handle.release();
            /* Log.d is below the production level, so a permanently failing start used to be
             * completely silent. Say it once at INFO instead. */
            if (!keyPanelMissLogged) {
                keyPanelMissLogged = true;
                Log.i(TAG, "DSIKeyPanel not available yet - retrying, MFW OK inactive until it is");
            }
            return false;
        }

        /* IMMICombiScreenChangeManager is OPTIONAL.  It belongs to the "MMI inside the cluster"
         * variant and is never registered on this A5-class unit, so requiring it left the module
         * permanently in the retry loop ("modules still pending after 10 s") and the MFW OK key
         * was never hooked at all - in either view.  When it is absent the map-tab gate falls
         * back to our own authoritative state, which onSteeringWheelOkPressed() re-checks anyway
         * (CarPlay owns the cluster AND RGI is active). */
        FrameworkRef.ServiceHandle combiHandle =
            fw.getServiceHandle(IMMICombiScreenChangeManager.class);
        if (combiHandle != null && !(combiHandle.service() instanceof IMMICombiScreenChangeManager)) {
            combiHandle.release();
            combiHandle = null;
        }

        DSIKeyPanel panel = (DSIKeyPanel)handle.service();
        IMMICombiScreenChangeManager manager = combiHandle == null
            ? null : (IMMICombiScreenChangeManager)combiHandle.service();
        ServiceRegistration registration = null;
        try {
            registration = fw.serviceManager().registerDSIListener(
                DSI_INSTANCE, DSIKeyPanelListener.class.getName(), listener);
            panel.setNotification(DSIKeyPanel.ATTR_KEY2, listener);

            keyPanelHandle = handle;
            combiManagerHandle = combiHandle;
            keyPanel = panel;
            combiManager = manager;
            listenerRegistration = registration;
            running = true;
            clearPendingSelects();
            synchronized (this) {
                if (longPressTimer == null) {
                    longPressTimer = new java.util.Timer(true);
                }
            }
            Log.i(TAG, "raw MFW OK listener ready (key=40 mapContext="
                + (manager == null ? "unavailable, using CarPlay RGI state" : "20") + ")");
            return true;
        } catch (Throwable t) {
            try { panel.clearNotification(DSIKeyPanel.ATTR_KEY2, listener); }
            catch (Throwable ignored) { }
            if (registration != null) {
                try { fw.serviceManager().unregisterService(registration); }
                catch (Throwable ignored) { }
            }
            handle.release();
            if (combiHandle != null) combiHandle.release();
            Log.w(TAG, "raw MFW listener start failed: " + t);
            return false;
        }
    }

    public synchronized void stop() {
        DSIKeyPanel panel = keyPanel;
        ServiceRegistration registration = listenerRegistration;
        FrameworkRef.ServiceHandle handle = keyPanelHandle;
        FrameworkRef.ServiceHandle combiHandle = combiManagerHandle;
        running = false;
        keyPanel = null;
        combiManager = null;
        listenerRegistration = null;
        keyPanelHandle = null;
        combiManagerHandle = null;
        clearPendingSelects();
        synchronized (this) {
            if (currentLongPressTask != null) {
                currentLongPressTask.cancel();
                currentLongPressTask = null;
            }
            if (longPressTimer != null) {
                try { longPressTimer.cancel(); } catch (Throwable ignored) {}
                longPressTimer = null;
            }
            longPressHandled = false;
        }

        if (panel != null) {
            try { panel.clearNotification(DSIKeyPanel.ATTR_KEY2, listener); }
            catch (Throwable t) { Log.w(TAG, "clear notification failed: " + t); }
        }
        if (registration != null) {
            try { registration.unregister(); }
            catch (Throwable t) { Log.w(TAG, "unregister failed: " + t); }
        }
        if (handle != null) handle.release();
        if (combiHandle != null) combiHandle.release();
    }

    /** Consume only the TerminalMode DDS_SELECT that originated as raw MFW key 40.
     *  The stock keyboard stack posts the collapsed HMI event asynchronously, so
     *  the short-lived marker is armed in the raw DSI callback first. */
    public static boolean consumeCollapsedSelect(KeyState state) {
        long now = System.currentTimeMillis();
        synchronized (SELECT_LOCK) {
            if (state != null && state.is(KeyState.PRESSED)) {
                boolean consume = pendingPressUntil >= now;
                pendingPressUntil = 0L;
                return consume;
            }
            if (state != null && state.is(KeyState.RELEASED)) {
                boolean consume = pendingReleaseUntil >= now;
                pendingReleaseUntil = 0L;
                return consume;
            }
            return false;
        }
    }

    private static void armCollapsedSelect(int rawState) {
        long until = System.currentTimeMillis() + COLLAPSED_SELECT_WINDOW_MS;
        synchronized (SELECT_LOCK) {
            if (rawState == KST_PRESSED) pendingPressUntil = until;
            else if (rawState == KST_RELEASED) pendingReleaseUntil = until;
        }
    }

    /** A real centre-console DDS event must never consume a stale wheel marker. */
    private static void clearCollapsedSelect(int rawState) {
        synchronized (SELECT_LOCK) {
            if (rawState == KST_PRESSED) pendingPressUntil = 0L;
            else if (rawState == KST_RELEASED) pendingReleaseUntil = 0L;
        }
    }

    private static void clearPendingSelects() {
        synchronized (SELECT_LOCK) {
            pendingPressUntil = 0L;
            pendingReleaseUntil = 0L;
        }
    }

    private boolean isConfirmedMapTab() {
        if (!running) return false;
        IMMICombiScreenChangeManager manager = combiManager;
        /* No combi manager on this variant: CarPlay owning the cluster with RGI up IS the
         * "map tab" here, and that is exactly what the handler below verifies. */
        if (manager == null) return ScreenModule.isConnected() && ScreenModule.isRgdActive();
        try {
            MMICombiDisplayStatus status = manager.getLastConfirmedDisplayStatus();
            return status != null
                && status.getMainContext() == MMICombiDisplayStatus.MAIN_CONTEXT_NAVIGATION_MAP;
        } catch (Throwable t) {
            Log.w(TAG, "cannot read confirmed VC context: " + t);
            return false;
        }
    }

    private final class RawKeyListener implements DSIKeyPanelListener {
        public void updateKey2(int keyboardId, int keyCode, int keyState,
                               int timeStamp, int validFlag) {
            if (!running || validFlag != ATTR_VALID) return;

            if (keyCode == KEY_DDS) {
                clearCollapsedSelect(keyState);
                return;
            }
            if (keyCode != KEY_MFW_ROLLER_LEFT
                    || (keyboardId != KBD_MFW && keyboardId != KBD_MFW_3GP)
                    || (keyState != KST_PRESSED && keyState != KST_RELEASED)) return;

            armCollapsedSelect(keyState);

            if (keyState == KST_PRESSED) {
                /* The 5 s hold toggles the cluster map whenever a CarPlay session is connected; it needs
                 * neither route guidance nor a VC map tab (this car has no combi manager to tell us). */
                boolean connectedNow = ScreenModule.isConnected();
                Log.i(TAG, "MFW left roller PRESSED (board=" + keyboardId + " connected=" + connectedNow + ")");
                if (!connectedNow) return;
                synchronized (SteeringWheelInputModule.this) {
                    if (currentLongPressTask != null) {
                        currentLongPressTask.cancel();
                        currentLongPressTask = null;
                    }
                    longPressHandled = false;
                    final java.util.TimerTask task = new java.util.TimerTask() {
                        public void run() {
                            try {
                                synchronized (SteeringWheelInputModule.this) {
                                    if (currentLongPressTask != this || !running) return;
                                    longPressHandled = true;
                                }
                                Log.i(TAG, "MFW left roller long press triggered (" + LONG_PRESS_DURATION_MS + " ms)");
                                ScreenModule.onSteeringWheelLongPressed();
                            } catch (Throwable t) {
                                Log.w(TAG, "unhandled exception in long press task: " + t);
                            }
                        }
                    };
                    currentLongPressTask = task;
                    try {
                        if (longPressTimer == null) {
                            longPressTimer = new java.util.Timer(true);
                        }
                        longPressTimer.schedule(task, LONG_PRESS_DURATION_MS);
                    } catch (Throwable t) {
                        Log.w(TAG, "failed to schedule long press timer: " + t);
                    }
                }
                return;
            }

            if (keyState == KST_RELEASED) {
                boolean wasHandled;
                synchronized (SteeringWheelInputModule.this) {
                    if (currentLongPressTask != null) {
                        currentLongPressTask.cancel();
                        currentLongPressTask = null;
                    }
                    wasHandled = longPressHandled;
                    longPressHandled = false;
                }
                Log.i(TAG, "MFW left roller RELEASED (board=" + keyboardId + " wasLongPress=" + wasHandled + ")");
                if (!wasHandled) {
                    // Short click (< LONG_PRESS_DURATION_MS): trigger route-info ETA / Street toggle
                    boolean mapTab = isConfirmedMapTab();
                    Log.i(TAG, "MFW OK short-pressed board=" + keyboardId + " mapTab=" + mapTab);
                    if (mapTab) {
                        ScreenModule.onSteeringWheelOkPressed();
                    }
                }
            }
        }

        public void asyncException(int errorCode, String errorString, int requestType) { }
        public void updateEncoder2(int keyboardId, int keyCode, int steps, int subSteps, int validFlag) { }
        public void updateDisplayTurnMechStatus(int state, int validFlag) { }
        public void updateRecognizerLanguage2(int keyboardId, String language, int languageCode, int validFlag) { }
        public void updateRecognizerMode(int keyboardId, int mode, int validFlag) { }
        public void updateCharacterEvent2(int keyboardId, String[] characters, int[] confidence, int validFlag) { }
        public void updateGesture2(int keyboardId, int gesture, int x, boolean flag, int y,
                                   int z, int a, int b, int c, int validFlag) { }
        public void genericSettingResponse(int setting, int value, int result) { }
        public void updateProximity(int keyboardId, int value, int validFlag) { }
        public void updateAdvancedProximity(int a, int b, int c, int d, int e,
                                            int f, int g, int h, int i, int validFlag) { }
        public void lastKey(int keyboardId, int keyCode, int keyState) { }
        public void updateKeyboardType(int keyboardType, int validFlag) { }
        public void updateTouchSensitiveArea(int keyboardId, int x, int y,
                                             int width, int height, int validFlag) { }
        public void getVersionInfo(int keyboardId, int component, String version) { }
        public void updateInputPanelReady(int keyboardId, int startupState, int validFlag) { }
        public void getProperty(int keyboardId, int property, int index,
                                int validFlag, byte[] value) { }
    }
}
