#!/bin/bash
#
# Build the canonical CarPlay Java patch — in Docker (no host JDK required).
#
#   ./scripts/build_java.sh
#
# Input:  java_patch/   +   ../../Tools/jxe2jar   (stock jar + OSGi libs)
# Output: build/carplay_hook.jar
#
# Compiles against MU1316-final.jar + OSGi, target 1.4 (jclfoun11 = Foundation 1.1),
# inside a pinned JDK 8 container so the build does not depend on a host JVM.
#
# Debug vs release:
#   ./scripts/build_java.sh                     debug build (default): RGI-DIAG diagnostics kept
#   CARPLAY_RELEASE=1 ./scripts/build_java.sh   release build: every debug-only piece is stripped
# In release mode com.luka.carplay.BuildFlags is generated with DIAG=false, javac folds every
# `if (BuildFlags.DIAG)` call site away, RgiDiag.class is removed from the jar, and the build
# FAILS if RgiDiag.class or the text "RGI-DIAG" is still anywhere in the jar.  The build mode is
# recorded in build/carplay_hook.mode so scripts/package_release.sh can refuse a mismatched jar.
#
# NOTE: MU1316-final.jar is the author's own decompiled stock HMI jar
# (../../Tools/jxe2jar/out/). Yours may be named or located differently - point
# STOCK_JAR below and the CP line inside the container at your own stock jar.
set -e

[ "$#" -eq 0 ] || { echo "usage: ./scripts/build_java.sh"; exit 2; }

IMG=eclipse-temurin:8-jdk-jammy
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLS_DIR="$(cd "$PROJECT_DIR/../../Tools/jxe2jar" && pwd)"

STOCK_JAR="$TOOLS_DIR/out/MU1316-final.jar"
[ -f "$STOCK_JAR" ] || { echo "ERROR: $STOCK_JAR not found"; exit 1; }
[ -d "$PROJECT_DIR/java_patch" ] || { echo "ERROR: java_patch/ not found"; exit 1; }

# Reproducible build identity is computed on the host (git lives here), passed into the container.
BUILD_ID_RAW=${CARPLAY_BUILD_ID:-$(git -C "$PROJECT_DIR" describe --always --dirty 2>/dev/null || echo unknown)}
BUILD_ID=$(printf '%s' "$BUILD_ID_RAW" | tr -cd 'A-Za-z0-9._-')

# CARPLAY_RELEASE=1 -> release; anything else (unset, 0, empty) -> debug.
if [ "${CARPLAY_RELEASE:-0}" = "1" ]; then
  BUILD_MODE=release; DIAG=false
else
  BUILD_MODE=debug; DIAG=true
fi
# BuildFlags is generated (never committed), like CarPlayApp's BUILD_ID; it lives under the
# project dir so the Docker container sees it as /src/build/genflags.
GENFLAGS_DIR="$PROJECT_DIR/build/genflags"
rm -rf "$GENFLAGS_DIR"; mkdir -p "$GENFLAGS_DIR/com/luka/carplay"
{
  echo "package com.luka.carplay;"
  echo ""
  echo "/** GENERATED by scripts/build_java.sh - do not edit. Build mode: $BUILD_MODE. */"
  echo "public final class BuildFlags {"
  echo "    private BuildFlags() { }"
  echo "    /** Debug-only diagnostics (RgiDiag). False in a CARPLAY_RELEASE=1 build. */"
  echo "    public static final boolean DIAG = $DIAG;"
  echo "}"
} > "$GENFLAGS_DIR/com/luka/carplay/BuildFlags.java"
rm -f "$PROJECT_DIR/build/carplay_hook.mode"

# Release gate: the jar must hold no RgiDiag class and no "RGI-DIAG" text.
verify_release_jar() {
  jar_file=$1
  command -v unzip >/dev/null 2>&1 || { echo "ERROR: unzip is required to verify a release build"; return 1; }
  if unzip -l "$jar_file" | grep -q 'RgiDiag'; then
    echo "ERROR: release jar contains RgiDiag:"; unzip -l "$jar_file" | grep 'RgiDiag'; return 1
  fi
  vdir=$(mktemp -d)
  ( cd "$vdir" && unzip -q "$jar_file" ) || { rm -rf "$vdir"; echo "ERROR: cannot unpack $jar_file"; return 1; }
  vlist=$(mktemp)
  find "$vdir" -name '*.class' -type f > "$vlist"
  vcount=$(wc -l < "$vlist" | tr -d ' ')
  if [ "$vcount" -eq 0 ]; then
    rm -rf "$vdir" "$vlist"; echo "ERROR: $jar_file has no .class entries (empty or wrong jar)"; return 1
  fi
  if [ ! -f "$vdir/com/luka/carplay/rgd/BAPBridge.class" ]; then
    rm -rf "$vdir" "$vlist"; echo "ERROR: $jar_file lacks com/luka/carplay/rgd/BAPBridge.class (wrong jar?)"; return 1
  fi
  # Scan EVERY class (nested ones included) for the debug text and for any RgiDiag reference (an
  # unguarded call site leaves a constant-pool reference even without RgiDiag.class).  grep exit
  # 1 = no match (good), 0 = found (fail), anything else = an error, which also fails the build.
  while IFS= read -r vclass; do
    [ -r "$vclass" ] || { echo "ERROR: cannot read extracted ${vclass#$vdir/}"; rm -rf "$vdir" "$vlist"; return 1; }
    if grep -qa 'RGI-DIAG' "$vclass"; then vrc=0; else vrc=$?; fi
    case $vrc in
      0) echo "ERROR: release jar still contains the text RGI-DIAG in ${vclass#$vdir/}"; rm -rf "$vdir" "$vlist"; return 1 ;;
      1) ;;
      *) echo "ERROR: grep failed (status $vrc) on ${vclass#$vdir/}"; rm -rf "$vdir" "$vlist"; return 1 ;;
    esac
    if grep -qa 'RgiDiag' "$vclass"; then vrc=0; else vrc=$?; fi
    case $vrc in
      0) echo "ERROR: ${vclass#$vdir/} references RgiDiag (unguarded call site?)"; rm -rf "$vdir" "$vlist"; return 1 ;;
      1) ;;
      *) echo "ERROR: grep failed (status $vrc) on ${vclass#$vdir/}"; rm -rf "$vdir" "$vlist"; return 1 ;;
    esac
  done < "$vlist"
  rm -f "$vlist"
  rm -rf "$vdir"
  echo "Release check OK: no RgiDiag class, no RGI-DIAG text in $jar_file"
}

if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  USE_DOCKER=1
elif command -v sg >/dev/null 2>&1 && sg docker -c "docker info" >/dev/null 2>&1; then
  exec sg docker -c "$0 $*"
else
  USE_DOCKER=0
fi

if [ "$USE_DOCKER" -eq 1 ]; then
  echo "=== CarPlay Java Patch Build (Docker $IMG) ==="

  docker run --rm \
    -v "$PROJECT_DIR":/src \
    -v "$TOOLS_DIR":/tools:ro \
    -e BUILD_ID="$BUILD_ID" \
    -e BUILD_MODE="$BUILD_MODE" \
    "$IMG" bash -c '
    set -e
    SRC=/src/java_patch
    OUT=/src/build/java/classes
    OUTJAR=/src/build/carplay_hook.jar
    CP="/tools/out/MU1316-final.jar:/tools/libs/org.osgi.framework-1.10.0.jar:/tools/libs/org.osgi.util.tracker-1.5.4.jar"

    rm -rf /src/build/java; mkdir -p "$OUT" /src/build
    SRCLIST=$(mktemp)
    find "$SRC" -name "*.java" -type f > "$SRCLIST"
    printf "%s\n" "/src/build/genflags/com/luka/carplay/BuildFlags.java" >> "$SRCLIST"
    echo "Compiling $(wc -l < "$SRCLIST" | tr -d " ") files (target 1.4)..."

    # Generate a CarPlayApp copy with the real BUILD_ID; never edit the source tree.
    GEN=$(mktemp -d)
    mkdir -p "$GEN/com/luka/carplay/core"
    sed "s/@BUILD_ID@/$BUILD_ID/g" "$SRC/com/luka/carplay/core/CarPlayApp.java" > "$GEN/com/luka/carplay/core/CarPlayApp.java"
    grep -v "/com/luka/carplay/core/CarPlayApp.java$" "$SRCLIST" > "$SRCLIST.tmp"; mv "$SRCLIST.tmp" "$SRCLIST"
    printf "%s\n" "$GEN/com/luka/carplay/core/CarPlayApp.java" >> "$SRCLIST"

    javac -source 1.4 -target 1.4 -cp "$CP" -sourcepath "$GEN:/src/build/genflags:$SRC" -d "$OUT" -Xlint:-options @"$SRCLIST"
    # Release: RgiDiag is unreferenced (DIAG=false folded every call away) - drop its classes.
    if [ "$BUILD_MODE" = release ]; then rm -f "$OUT"/com/luka/carplay/rgd/RgiDiag*.class; fi
    # Compact generated metrics/Unicode tables (VC route text) live inside the jar.
    cp -R /src/java_resources/. "$OUT/"
    (cd "$OUT" && jar cf "$OUTJAR" .)
    rm -rf /src/build/java
  '
else
  if [ "$(uname)" = "Darwin" ]; then
    JDK_DIR="$TOOLS_DIR/jvms/zulu8.78.0.19-ca-jdk8.0.412-macosx_aarch64/zulu-8.jdk/Contents/Home"
  else
    JDK_DIR="$TOOLS_DIR/jvms/zulu8.78.0.19-ca-jdk8.0.412-linux_x64"
  fi
  [ -x "$JDK_DIR/bin/javac" ] || { echo "ERROR: Neither docker nor $JDK_DIR/bin/javac found"; exit 1; }
  echo "=== CarPlay Java Patch Build (Local JDK $JDK_DIR) ==="

  SRC="$PROJECT_DIR/java_patch"
  OUT="$PROJECT_DIR/build/java/classes"
  OUTJAR="$PROJECT_DIR/build/carplay_hook.jar"
  CP="$STOCK_JAR:$TOOLS_DIR/libs/org.osgi.framework-1.10.0.jar:$TOOLS_DIR/libs/org.osgi.util.tracker-1.5.4.jar"

  rm -rf "$PROJECT_DIR/build/java"
  mkdir -p "$OUT" "$PROJECT_DIR/build"
  SRCLIST=$(mktemp)
  find "$SRC" -name "*.java" -type f > "$SRCLIST"
  printf "%s\n" "$GENFLAGS_DIR/com/luka/carplay/BuildFlags.java" >> "$SRCLIST"
  echo "Compiling $(wc -l < "$SRCLIST" | tr -d " ") files (target 1.4)..."

  GEN=$(mktemp -d)
  mkdir -p "$GEN/com/luka/carplay/core"
  sed "s/@BUILD_ID@/$BUILD_ID/g" "$SRC/com/luka/carplay/core/CarPlayApp.java" > "$GEN/com/luka/carplay/core/CarPlayApp.java"
  grep -v "/com/luka/carplay/core/CarPlayApp.java$" "$SRCLIST" > "$SRCLIST.tmp"; mv "$SRCLIST.tmp" "$SRCLIST"
  printf "%s\n" "$GEN/com/luka/carplay/core/CarPlayApp.java" >> "$SRCLIST"

  "$JDK_DIR/bin/javac" -source 1.4 -target 1.4 -cp "$CP" -sourcepath "$GEN:$GENFLAGS_DIR:$SRC" -d "$OUT" -Xlint:-options @"$SRCLIST"
  # Release: RgiDiag is unreferenced (DIAG=false folded every call away) - drop its classes.
  if [ "$BUILD_MODE" = release ]; then rm -f "$OUT"/com/luka/carplay/rgd/RgiDiag*.class; fi
  # Compact generated metrics/Unicode tables (VC route text) live inside the jar.
  cp -R "$PROJECT_DIR/java_resources/." "$OUT/"
  (cd "$OUT" && "$JDK_DIR/bin/jar" cf "$OUTJAR" .)
  rm -rf "$PROJECT_DIR/build/java" "$GEN" "$SRCLIST"
fi

rm -rf "$GENFLAGS_DIR"
if [ "$BUILD_MODE" = release ]; then
  verify_release_jar "$PROJECT_DIR/build/carplay_hook.jar" || { rm -f "$PROJECT_DIR/build/carplay_hook.jar"; exit 1; }
fi
printf '%s\n' "$BUILD_MODE" > "$PROJECT_DIR/build/carplay_hook.mode"
echo "Output: $PROJECT_DIR/build/carplay_hook.jar"
echo "Build ID: $BUILD_ID"
echo "Build mode: $BUILD_MODE"
